### PR TITLE
mrc-3755: Comparison barchart is showing the wrong indicator for ANC age matched indicators

### PR DESCRIPTION
**Pull request by r-ash**

### CODE REVIEW

**Review by LekanAnni — CHANGES_REQUESTED** [review]
Could you add a regression test ?

**Comment by r-ash** [comment]
hintr PR https://github.com/mrc-ide/hintr/pull/418

**Comment by r-ash** [comment]
> Could you add a regression test ?

Added a test which checks that the metadata contains metadata for each indicator only once for each plot type. This would have caught the problem and should catch any similar issues in future.

**Comment by r-ash** [comment]
Screenshot_20221107_114648
This is looking good on dev!

**Review by LekanAnni — APPROVED** [review]
LGTM 👍 

Thanks

**Pull request merged**
