### PR TITLE
improve aggregate_art() function to handle ART data from multiple levels

### PR DESCRIPTION
**Pull request by rtesra**
This PR fixes a bug in the input data aggregation scripts for edge cases such as Mozambique where ART data was provided at admin1 from 2014-2016 and admin3 from 2017-onwards. 

Previous behaviour:
* Aggregate data up from lowest level available programme data
* Use aggregated data to select and tag naomi inputs

This PR:
* Process data and split by year
* Running aggregation script, subsetting data at the finest stratification available for each year 
* Use aggregated data to select and tag naomi inputs

This accounts for the following edge cases:
* Data provided at different area levels for different  time periods
* Data provided at multiple area levels for different time periods

### CODE REVIEW

**Comment by jeffeaton** [comment]
Thanks for this. Could you please add a test?  That will also create an example that I can step through to see the logic when reviewing.

For creating a test, suggest writing a test that read the demo data, constructs demo data similar to the problematic Mozambique data, and saves that as a temporary .csv file. E.g. how this test is structured: https://github.com/mrc-ide/naomi/blob/3ffd73bc9dd5a01dae5ed61a2251c5363c86a968/tests/testthat/test-read-data.R#L96-L109

**Review by jeffeaton — CHANGES_REQUESTED** [review]
Thanks for this. I have slightly elaborated the test (it works, just added assertions to confirm it).

Two more requests as discussed:
* Please handle case where an already aggregated data set is uploaded + add a test for that. 
  * I _think_ the way I would handle that is to first subset data at the finest stratification, and then proceed with the aggregation. Do you agree?
* Could the same issue affect aggregation of the ANC testing data set? Does that need handling + testing?

**Review by jeffeaton — CHANGES_REQUESTED** [review]
I have traced back the issue giving rise to the error here:
https://github.com/mrc-ide/naomi/blob/cc19d76a566fd2ede574620cae3ec3314669214a/tests/testthat/test-model-fit.R#L53-L54
```r
>   fit <- fit_tmb(tmb_inputs, outer_verbose = FALSE)
Error in stats::nlminb(obj$par, obj$fn, obj$gr, control = list(trace = trace,  : 
  NA/NaN gradient evaluation
```

The issue is that, when called here in `select_naomi_data()`: https://github.com/mrc-ide/naomi/blob/cc19d76a566fd2ede574620cae3ec3314669214a/R/model.R#L886,
the new `aggregate_anc()` function creates `0` values for the indicator `anc_clients_pys_offset` for locations which do not have any ANC data:
```r
Browse[4]> anc_model_mf %>%
      dplyr::filter(
        year %in% !!year,
        indicator %in% c("anc_clients_x", "anc_clients_pys_offset")
      )
+ # A tibble: 8 × 6
  area_id      age_group  year sex    indicator              value
  <chr>        <chr>     <dbl> <chr>  <chr>                  <dbl>
1 MWI_4_1_demo Y015_049   2018 female anc_clients_pys_offset     0
2 MWI_4_2_demo Y015_049   2018 female anc_clients_pys_offset     0
3 MWI_4_3_demo Y015_049   2018 female anc_clients_x           5924
4 MWI_4_3_demo Y015_049   2018 female anc_clients_pys_offset     0
5 MWI_4_4_demo Y015_049   2018 female anc_clients_pys_offset     0
6 MWI_4_5_demo Y015_049   2018 female anc_clients_pys_offset     0
7 MWI_4_6_demo Y015_049   2018 female anc_clients_pys_offset     0
8 MWI_4_7_demo Y015_049   2018 female anc_clients_pys_offset     0
```

Consequently, the `pivot_wider()` in `anc_testing_clients_mf()`: https://github.com/mrc-ide/naomi/blob/cc19d76a566fd2ede574620cae3ec3314669214a/R/model.R#L1368-L1376
creates rows for each area, with `NA` values for the `anc_clients_x` column:
```r
Browse[4]>     anc_sub <- anc_model_mf %>%
      dplyr::filter(
        year %in% !!year,
        indicator %in% c("anc_clients_x", "anc_clients_pys_offset")
      ) %>%
      tidyr::pivot_wider(names_from = "indicator", values_from = "value") %>%
      dplyr::mutate(obs_idx = dplyr::row_number()) %>%
      dplyr::select("area_id", "sex", "age_group","obs_idx","anc_clients_x", "anc_clients_pys_offset")

+ Browse[4]> anc_sub
# A tibble: 7 × 6
  area_id      sex    age_group obs_idx anc_clients_x anc_clients_pys_offset
  <chr>        <chr>  <chr>       <int>         <dbl>                  <dbl>
1 MWI_4_1_demo female Y015_049        1            NA                      0
2 MWI_4_2_demo female Y015_049        2            NA                      0
3 MWI_4_3_demo female Y015_049        3          5924                      0
4 MWI_4_4_demo female Y015_049        4            NA                      0
5 MWI_4_5_demo female Y015_049        5            NA                      0
6 MWI_4_6_demo female Y015_049        6            NA                      0
7 MWI_4_7_demo female Y015_049        7            NA                      0
```

**Review by r-ash — APPROVED** [review]
hintr is passing so looks good from my end

**Review by jeffeaton — APPROVED** [review]
Thanks this looks good.  Approving. But I have just merged master v2.8.0 into this. Let's confirm it passes tests before merging.

**Pull request merged**
